Add missing header to InstructionCombining.cpp; fixes Crystal build
which failed with "undefined reference to 'LLVMInitializeInstCombine'"

https://bugs.llvm.org/show_bug.cgi?id=35947